application: my-kanojo
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/.*
  script: kanojo_handler.py 
  login: admin
- url: /.*
  script: kanojo_handler.py 

inbound_services:
- xmpp_message
- mail
